name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        id: lol
        with:
           fetch-depth: 0
      - name: Get changes
        run: |
         echo "git diff --name-only ${{ github.event.before }} ${{ github.event.after }}"
          